version: 2
updates:

- package-ecosystem: nuget
  directory: "/server"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 5
  
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 5
  versioning-strategy: lockfile-only