version: '3.7'

services:
  agentd:
    image: mrosenbjerg/agentd-server:latest
    container_name: agentd-server
    ports:
      - "5000:5000"
    environment:
      - TZ=Europe/Copenhagen
    volumes:
      - ./server/AgentDeploy.ExternalApi/scripts:/app/scripts:ro
      - ./server/AgentDeploy.ExternalApi/tokens:/app/tokens:ro
      