name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore
      
    - name: Run unit test suite
      run: dotnet test -c Release --filter TestCategory=Unit --no-build --verbosity normal
      
    - name: Run E2E test suite
      run: dotnet test -c Release --filter TestCategory=E2E --no-build --verbosity normal
