name: CI

on:
  push:
    branches: [ main ]
    paths:
    - server/**
    - client/**
  pull_request:
    branches: [ main, release ]
    paths:
    - server/**
    - client/**

jobs:
  build:
    env:
      server_dir: ./server
      client_dir: ./client
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore NuGet packages
      working-directory: ${{ env.server_dir }}
      run: dotnet restore
        
    - name: Restore dependencies
      working-directory: ${{ env.server_dir }}
      run: dotnet restore
      
    - name: Build
      working-directory: ${{ env.server_dir }}
      run: dotnet build -c Release --no-restore
      
    - name: Run unit test suite
      working-directory: ${{ env.server_dir }}
      run: dotnet test -c Release --filter TestCategory=Unit --collect "XPlat Code Coverage" --logger GitHubActions --no-build --verbosity normal
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
      with: 
        node-version: 8.x
        
    - name: Install NPM packages
      working-directory: ${{ env.client_dir }}
      run: npm ci
      
    - name: Run E2E test suite
      working-directory: ${{ env.server_dir }}
      run: dotnet test -c Release --filter TestCategory=E2E --collect "XPlat Code Coverage" --logger GitHubActions --no-build --verbosity normal
