name: Update images

on:
  schedule:
    - cron: 0 4 * * 6

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build agentd server image
      run: |
        SERVER_VERSION=$(cat server/AgentDeploy.ExternalApi/AgentDeploy.ExternalApi.csproj | grep '<PackageVersion>' | sed 's/.*<PackageVersion>\(.*\)<\/PackageVersion>/\1/' | tr -d '[[:space:]]' | sed -E s/\.[0-9]+$//)
        MAJOR_SERVER_VERSION=$(echo "$SERVER_VERSION" | sed -E s/\.[0-9]+$//)

        docker build -f container/server/Dockerfile \
          -t "mrosenbjerg/agentd-server:${SERVER_VERSION}" \
          -t "mrosenbjerg/agentd-server:${MAJOR_SERVER_VERSION}" \
          server
    
    - name: Build agentd client image
      run: |
        CLIENT_VERSION=$(cat client/package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]' | sed -E s/\.[0-9]+$//)
        MAJOR_CLIENT_VERSION=$(echo "$CLIENT_VERSION" | sed -E s/\.[0-9]+$//)
        
        docker build -f container/client/Dockerfile \
          -t "mrosenbjerg/agentd-client:${CLIENT_VERSION}" \
          -t "mrosenbjerg/agentd-client:${MAJOR_CLIENT_VERSION}" \
          client
    
    - name: Login to Docker Hub
      run: docker login --username mrosenbjerg --password ${{ secrets.DOCKER_TOKEN }}
    
    - name: Push agentd server image
      run: docker push --all-tags mrosenbjerg/agentd-server
    
    - name: Push agentd client image
      run: docker push --all-tags mrosenbjerg/agentd-client
